# Publish workflow for DaxLib.Sample package
#
# This workflow creates a branch in the upstream repository sql-bi/daxlib to
# add a new version of the package. After execution, access the sql-bi/daxlib
# repository and manually create a Pull Request from the newly created branch.
#
# TODO:
# - Automate the PR creation

name: publish-daxlib-sample

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the current repository
      - name: checkout source
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: source-repo

      # Checkout the upstream repository sql-bi/daxlib
      - name: checkout upstream
        uses: actions/checkout@v4
        with:
          repository: sql-bi/daxlib
          path: upstream-repo
          token: ${{ secrets.DAXLIB_TOKEN }} # Required to push changes
        
      # Configure Git
      - name: git config
        working-directory: upstream-repo
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      # Extract package version from manifest
      - name: get package version
        id: get_package_version
        working-directory: source-repo
        run: |
          VERSION=$(jq -r '.version' src/manifest.daxlib)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Package version: $VERSION"

      # Create the feature branch for the new version
      - name: create release branch
        working-directory: upstream-repo
        run: git checkout -b "daxlibsample/release-${{ steps.get_package_version.outputs.version }}"
              
      # Create the package folder for the new version
      - name: create package folder
        working-directory: upstream-repo
        run: mkdir -p "packages/d/daxlib.sample/${{ steps.get_package_version.outputs.version }}"

      # Copy package files to the new folder
      - name: copy package files
        run: cp -rv source-repo/src/* "upstream-repo/packages/d/daxlib.sample/${{ steps.get_package_version.outputs.version }}/"

      # Stage and commit changes
      - name: git commit changes
        working-directory: upstream-repo
        run: git add -A && git commit -m "Add package DaxLib.Sample version ${{ steps.get_package_version.outputs.version }}"

      # Push branch to upstream repository
      - name: git push upstream
        working-directory: upstream-repo
        run: git push origin "daxlibsample/release-${{ steps.get_package_version.outputs.version }}"

